baseURL = "https://food2.nd.gl/"
languageCode = "en-us"
title = "Indy's Foods"
theme = "baes"
uglyURLs = true
copyright = "Copyright © 2024, Indy"
timeout = "10m"

[params]

[params.author]
  email = "indy@ishere.com"
  name= "Indy"

[menus]
[module]
[[module.mounts]]
  source = 'assets'
  target = 'assets'

[[module.mounts]]
  source = 'media'
  target = 'assets'