theme: jekyll-theme-slate

collections:
  recipes:
    output: true
    permalink: /:collection/:path/

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default
      read_time: true
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: default
      read_time: true
  - scope:
      path: "_recipes"
      type: recipes
    values:
      layout: default
      read_time: true
