name: Deploy Hugo site
on:
  push:
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.121.2
    steps:
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb
      - name: Install Dart Sass Embedded
        run: sudo snap install dart-sass-embedded
      #- name: Configure AWS Credentials
      #  uses: aws-actions/configure-aws-credentials@v1
      #  with:
      #    aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #    aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #    aws-region: us-west-2
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      #- name: sync Media from S3
      #  run: aws s3 sync s3://food.nd.gl-media ./media/ --delete
      - name: Build with Hugo
        env:
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        run: |
          hugo \
            --minify \
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public
      #- name: sync Media from S3
      #  run: aws s3 sync s3://food.nd.gl-media s3://food.nd.gl/media --delete --copy-props none
      #- name: Deploy static site to S3 bucket
      #  run: aws s3 sync ./public/ s3://food.nd.gl --delete --exclude 'media/*'
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy GithubPages
        id: deployment
        uses: actions/deploy-pages@v4
